### PR TITLE
HotReload Macro

### PR DESCRIPTION
**Pull request by Wouter01**
Hey there! I'm a happy user of this library, but always needing to add `@ObserveInjection` and `.enableInjection()` felt a bit repetitive. I wrote a small macro which does this for you, which reduces the boilerplate even more.

With this macro, you're able to write

```swift
@HotReload
struct ExampleView: View {
    var body: some View {
        Text("Hello world!")
    }
}
```

Instead of:
```swift
struct ExampleView: View {
    
    @ObserveInjection var observe
    
    var body: some View {
        Text("Hello world!")
            .enableInjection()
    }
}
```

### Macro details
After macro expansion, the struct will look like this:

```swift
struct ExampleView: View {
    var body: some View {
        Text("Hello world!")
    }

#if DEBUG

@ObserveInjection private var __observeInjection

typealias Body = AnyView

@_implements(View, body)
@_disfavoredOverload
var __body: AnyView {
    AnyView(body)
}
#endif
}
```

**Some notes**
- `__body` acts as a replacement for the existing `body` implementation. Essentially, we have two `body` implementations. `__body` will be picked instead of `body`, as its type matches the `Body` type which we explicitly set to `AnyView`. The macro enforces that the `body` type cannot be `AnyView`, as that would cause conflicts.
- `@_disfavoredOverload` is added, so `body` has preference over `__body` when used inside `__body`. Confusing but without it it'll pick `__body` and cause infinite loops :)
- `_ = InjectConfiguration.load` isn't called in the body, because it should already be loaded in by `ObserveInjection`
- The generated code is wrapped in `#if DEBUG` so it's excluded from production builds

**Other things worth mentioning**
- As macros _can_ be slow in some setups, the macro is disabled by default, and can be enabled with the `HotReloadMacro` package trait. If it's not specified, swift-syntax won't be resolved and compiled. I'm not sure if Xcode supports specifying traits yet, so not sure what the best default would be.
In a swift package, the macro can be enabled by specifying the trait in the dependency.
`.package(url: "https://github.com/Wouter01/Inject", branch: "main", traits: ["HotReloadMacro"])`

- The `package.swift` minimum swift version has been bumped to 6.1 to support macros and traits. A `package@swift-5.3.swift` file has been added which _should_ still support earlier swift versions, although I did not test this.
- There's a bunch of swift concurrency errors because of bumping the tools version to 6.1. As they are unrelated to this PR, I've disabled them by setting the swift language mode back to v5.

If you have any suggestions or concerns let me know!

### CODE REVIEW

**Comment by johnno1962** [comment]
Hi, thanks very much for this but I'd be personally would be against including a macro in Inject due to the performance concerns only recently addressed.  If you want to furnish a macro I'd suggest creating another repo with Inject as a dependency so the two can be separate and Inject can remain lightweight.

**Comment by Wouter01** [comment]
I'm not sure if that's an issue with the trait? As mentioned, the trait is disabled by default, which also means that if you don't want to use the macro, swift-syntax isn't included in the dependency tree, so it's not fetched or compiled. Inject would then be as lightweight as it is today.

**Comment by johnno1962** [comment]
Your call @krzysztofzablocki, the change would bring the minimum supported Xcode to 16.3

**Comment by Wouter01** [comment]
It should still support older Xcode versions, as there's two `package.swift` files now: one when the swift compiler >= 6.1 and a fallback for compilers >= 5.3

**Comment by johnno1962** [comment]
@Wouter01, you're quite right Xcode 16.2 does support your package (I tested it), I can see you've thought this through. 

Update: I've been trying Xcode 16.4 and 26.1.1 (without the trait "HotReloadMacro" and I get an error:
I appreciate what you're trying to do but I personally wouldn't complicate this repo with a macro.
```
Ld /Users/jh/Library/Developer/Xcode/DerivedData/Bookworm-ajsuaampuqlxrjfdypvdeumtdcoe/Build/Products/Debug/HotReloadMacro normal (in target 'HotReloadMacro' from project 'Inject')
    cd /Users/jh/Library/Developer/Xcode/DerivedData/Bookworm-ajsuaampuqlxrjfdypvdeumtdcoe/SourcePackages/checkouts/Inject
    /Volumes/Data3/PreviousContent/Xcode2611.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Xlinker -reproducible -target arm64-apple-macos10.15 -isysroot /Volumes/Data3/PreviousContent/Xcode2611.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.1.sdk -O0 -w -L/Users/jh/Library/Developer/Xcode/DerivedData/Bookworm-ajsuaampuqlxrjfdypvdeumtdcoe/Build/Intermediates.noindex/EagerLinkingTBDs/Debug -L/Users/johnholdsworth/Library/Developer/Xcode/DerivedData/Bookworm-ajsuaampuqlxrjfdypvdeumtdcoe/Build/Products/Debug -L/Volumes/Data3/PreviousContent/Xcode2611.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F/Users/jh/Library/Developer/Xcode/DerivedData/Bookworm-ajsuaampuqlxrjfdypvdeumtdcoe/Build/Intermediates.noindex/EagerLinkingTBDs/Debug -F/Users/jh/Library/Developer/Xcode/DerivedData/Bookworm-ajsuaampuqlxrjfdypvdeumtdcoe/Build/Products/Debug -iframework /Volumes/Data3/PreviousContent/Xcode2611.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -filelist /Users/johnholdsworth/Library/Developer/Xcode/DerivedData/Bookworm-ajsuaampuqlxrjfdypvdeumtdcoe/Build/Intermediates.noindex/Inject.build/Debug/HotReloadMacro.build/Objects-normal/arm64/HotReloadMacro.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -object_path_lto -Xlinker /Users/johnholdsworth/Library/Developer/Xcode/DerivedData/Bookworm-ajsuaampuqlxrjfdypvdeumtdcoe/Build/Intermediates.noindex/Inject.build/Debug/HotReloadMacro.build/Objects-normal/arm64/HotReloadMacro_lto.o -rdynamic -Xlinker -no_deduplicate -Xlinker -dependency_info -Xlinker /Users/jh/Library/Developer/Xcode/DerivedData/Bookworm-ajsuaampuqlxrjfdypvdeumtdcoe/Build/Intermediates.noindex/Inject.build/Debug/HotReloadMacro.build/Objects-normal/arm64/HotReloadMacro_dependency_info.dat -fobjc-link-runtime -L/Volumes/Data3/PreviousContent/Xcode2611.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/johnholdsworth/Library/Developer/Xcode/DerivedData/Bookworm-ajsuaampuqlxrjfdypvdeumtdcoe/Build/Intermediates.noindex/Inject.build/Debug/HotReloadMacro.build/Objects-normal/arm64/HotReloadMacro.swiftmodule @/Users/jh/Library/Developer/Xcode/DerivedData/Bookworm-ajsuaampuqlxrjfdypvdeumtdcoe/Build/Intermediates.noindex/Inject.build/Debug/HotReloadMacro.build/Objects-normal/arm64/HotReloadMacro-linker-args.resp -o /Users/jh/Library/Developer/Xcode/DerivedData/Bookworm-ajsuaampuqlxrjfdypvdeumtdcoe/Build/Products/Debug/HotReloadMacro

Undefined symbols for architecture arm64:
  "_main", referenced from:
      <initial-undefines>
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Wouter01** [comment]
Thanks for testing!
I understand your reasoning about why having the macro can give issues, so I'm fine with putting it in a separate package. I'll also leave it up to @krzysztofzablocki

**Comment by johnno1962** [comment]
But did you fix anything? At the moment it doesn't work when you add the package as a dependency using Xcode which is the common use case.

**Comment by Wouter01** [comment]
Checked:
- it's indeed not working on Xcode 16.4, I think there's something bugged in how the traits are interpreted, because all the dependencies (including swift-syntax) are fetched, even when the trait is disabled. Not sure if it's swift or Xcode related, but bumping the swift package definition to 6.2 should solve that (6.1 will then use the old package.swift definition without the macro)
- AFAIK Xcode still has no support for configuring package traits, so when the package is added as a dependency to an Xcode project, I don't think it's possible at the moment to enable the macro trait and use the macro. A workaround is to create a local package which has the Inject package as a dependency and enable the trait there and reexport.

**Comment by johnno1962** [comment]
Hi again, I'm going to close this on Monday unless @krzysztofzablocki intervenes rather than leave you hanging on the line.

I'd prefer this was not merged as:
1) Supporting Inject should not become supporting Xcode's new build system for macros. It's not hard to foresee problems.
2) I've recently learned macros can slow down user's builds as they introduce potentially slow type checking to every file in a target. This is because all sources in a target are lexed and parsed (the fast bit of compiling) but using a macro they need to be type checked before lexing can take place hence a macro used in one file can slow down the compile of _all other files_.

I'd also argue on KISS grounds that we should not make this repo more complicated than it needs to be.

**Comment by johnno1962** [comment]
As promised, closing this for now. I recommend making another repo for the macro with this one as a dependency.
